"""empty message

Revision ID: cd96954a4dd6
Revises: d14a52f9292f
Create Date: 2025-05-30 12:19:55.869829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd96954a4dd6'
down_revision: Union[str, None] = 'd14a52f9292f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone', 'price_inr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone', sa.Column('price_inr', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
