"""empty message

Revision ID: d14a52f9292f
Revises: 734b5b15aab5
Create Date: 2025-05-30 12:18:49.974362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14a52f9292f'
down_revision: Union[str, None] = '734b5b15aab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone', 'num_ratings')
    op.drop_column('phone', 'processor')
    op.drop_column('phone', 'front_cam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone', sa.Column('front_cam', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('phone', sa.Column('processor', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('phone', sa.Column('num_ratings', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
